# Site settings
title: "Arun Avanathan"
description: "Arun Avanathan"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Arun Avanathan"
resume_title:                   "Architect/Principal Engineer, <a href='https://intuit.com'>Intuit</a>"
resume_contact_email:           "arun.avanathan@gmail.com"
resume_contact_telephone:       "xxx-xxx-xxxx"
resume_contact_address:         "Mountain View, CA"
resume_header_contact_info: "Mountain View, CA | arun.avanathan@gmail.com"
resume_header_intro: "<p>20+ years experience in designing, building highly scalable applications, services using Open Source technologies such as Java, Spring, MySQL, NGinx, Tomcat, Jetty, Memcached on Linux. Skillset includes : </br>
<ul>
<li>Architecting & Building distributed applications in AWS</li>
<li>Staying Customer focussed, Driven by metrics</li>
<li>Expertise in building Backend services with familiarity to frontend technologies and user experience</li>
<li>Believes in Application Security to protect customer's data & privacy</li>
<li>Passionate about building platform as a Product and end to end automation</li>
</ul>
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/avanathan/resume"
  resume_twitter_url:           "http://twitter.com/the_arun"
  resume_dribbble_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/avanathan/"
  resume_website_url:           "http://github.com/avanathan"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
